# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfb491d699949368b95d27da32d0b05e"
name = "bannerpromo3"
handle = "bannerpromo3"
application_url = "https://transit-font-roberts-urban.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://transit-font-roberts-urban.trycloudflare.com/auth/callback",
  "https://transit-font-roberts-urban.trycloudflare.com/auth/shopify/callback",
  "https://transit-font-roberts-urban.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
